spring:
      data:
          mongodb:
                host: dev-lifecycle.kotsovolos.gr
                port: 27017
                database: cqrs_flux_dev
                username: cqrsFluxDev
                password: cqrsFluxDev

server:
      port: 8282

eureka:
      client:
            healthcheck:
                      enabled: true
            serviceUrl:
                      defaultZone: http://localhost:8061/eureka/
      instance:
              preferIpAddress: true
              instanceId: ${spring.cloud.client.hostname}:${server.port}
              leaseRenewalIntervalInSeconds: 1
              leaseExpirationDurationInSeconds: 2

micro:
     account:
             app:
                name: account-micro-dev