spring:
      cloud:
          gateway:
                discovery:
                        locator:
                               enabled: true
                routes:
                 - id: user-micro
                  uri: lb://user-micro
                  predicates:
                  - Path=/api/users/**
                  filters:
                  - RewritePath=/api/users/(?.*), /$\{path}
                - id: account-micro
                  uri: lb://account-micro
                  predicates:
                  - Path=/api/accounts/**
                  filters:
                  - RewritePath=/api/accounts/(?.*), /$\{path}
                - id: customer-micro
                  uri: lb://customer-micro
                  predicates:
                  - Path=/api/customers/**
                  filters:
                  - RewritePath=/api/customers/(?.*), /$\{path}

server:
      port: 8383

eureka:
      client:
            healthcheck:
                      enabled: true
            serviceUrl:
                      defaultZone: http://localhost:8061/eureka/
      instance:
              preferIpAddress: true
              instanceId: ${spring.cloud.client.hostname}:${server.port}
              leaseRenewalIntervalInSeconds: 1
              leaseExpirationDurationInSeconds: 2

micro:
     gateway:
             app:
                name: gateway-micro-dev
                logging:
                       appenders:
                                logstash:
                                        url: http://10.72.1.248:9200/_bulk